services:
  pc-a:
    build: ./pc-a
    container_name: pc-a
    hostname: pc-a
    tty: true
    stdin_open: true
    privileged: true
    networks:
      pc-a-network:
        ipv6_address: 2001:db8:1:1::20
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.disable_ipv6=0
     

  pc-b:
    build: ./pc-b
    container_name: pc-b
    hostname: pc-b
    tty: true
    stdin_open: true
    privileged: true
    networks:
      pc-b-network:
        ipv6_address: 2001:db8:1:2::20
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.disable_ipv6=0
   

  frr1:
    build: ./frr1
    container_name: frr1
    hostname: frr1
    tty: true
    stdin_open: true
    privileged: true
    networks:
      pc-a-network:
        ipv6_address: 2001:db8:1:1::10
      router-network:
        ipv6_address: 2001:db8:1:3::10
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.disable_ipv6=0
  
  frr2:
    build: ./frr2
    container_name: frr2
    hostname: frr2
    tty: true
    stdin_open: true
    privileged: true
    networks:
      pc-b-network:
        ipv6_address: 2001:db8:1:2::10
      router-network:
        ipv6_address: 2001:db8:1:3::20
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.disable_ipv6=0

networks:
  pc-a-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:db8:1:1::/64

  pc-b-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:db8:1:2::/64

  router-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:db8:1:3::/64